### ISSUE TITLE
Failed to write XXXX bytes.

### ISSUE THREAD

**Issue by aledr** [Icinga/icingaweb2-module-pdfexport#48]
## Describe the bug

Hi.

Any clue about this error?
I wasn't able to find the root cause.

```
#0 /usr/share/icingaweb2/modules/pdfexport/vendor/textalk/websocket/lib/Base.php(432): WebSocket\Base->throwException(String)
#1 /usr/share/icingaweb2/modules/pdfexport/vendor/textalk/websocket/lib/Base.php(219): WebSocket\Base->write(String)
#2 /usr/share/icingaweb2/modules/pdfexport/vendor/textalk/websocket/lib/Base.php(95): WebSocket\Base->sendFragment(Boolean, String, String, Boolean)
#3 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(554): WebSocket\Base->send(String)
#4 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(406): Icinga\Module\Pdfexport\HeadlessChrome->communicate(Object(WebSocket\Client), String, Array)
#5 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(319): Icinga\Module\Pdfexport\HeadlessChrome->printToPDF(String, String, Array)
#6 /usr/share/icinga-php/ipl/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): Icinga\Module\Pdfexport\HeadlessChrome->Icinga\Module\Pdfexport\{closure}(String)
#7 /usr/share/icinga-php/vendor/vendor/react/stream/src/ReadableResourceStream.php(146): Evenement\EventEmitter->emit(String, Array)
#8 /usr/share/icinga-php/vendor/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\ReadableResourceStream->handleData(Resource)
#9 /usr/share/icinga-php/vendor/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity(Integer)
#10 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(331): React\EventLoop\StreamSelectLoop->run()
#11 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/ProvidedHook/Pdfexport.php(98): Icinga\Module\Pdfexport\HeadlessChrome->toPdf()
#12 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportController.php(119): Icinga\Module\Pdfexport\ProvidedHook\Pdfexport->streamPdfFromHtml(Object(Icinga\Module\Pdfexport\PrintableHtmlDocument), String)
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->downloadAction()
#14 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#18 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#19 {main}
```

![image](https://user-images.githubusercontent.com/47945/143475085-a11ef23a-3943-4208-9a55-c4be484fdd25.png)

## Your Environment

* Module version: 0.10.0 (Git Commit 590bcfd3e54d3d4a4238d1daa04a86bcca749d21)
* Dependent module versions: icinga-php-library-0.7.0-1.icinga.noarch and icinga-php-thirdparty-0.10.0-2.icinga.noarch
* Icinga Web 2 version and modules (System - About): 2.9.4
* Chrome/Chromium version (`google-chrome --version`): Chromium 95.0.4638.69 stable
* Web browser and version: 
* PHP version used (`php --version`): 7.4.6
* Server operating system and version: openSUSE Leap 15.3

**Comment by nilmerg** [comment]
Does the log contain more info? If you're using a local chrome instance, you should see it's output there too. (Enable debug log to see that)

If it's a remote instance, it may also show something in its output.

Does it happen with an export of a normal list or is it a report made by the reporting module? Or even one made by Icinga DB Web?

**Comment by aledr** [comment]
Fixed changing from Chromium to Google Chrome.
